### ISSUE TITLE
Tech Blog 2

### ISSUE THREAD

**Issue by tinezekis** [chagers/chagers.github.io#5]
Hey Christine,

I guess we're supposed to be adding feedback as "issues", so here we are...

Your blog looks great and your website is awesome! I think the format is attractive and easy to navigate. In terms of the specific blog post I read (CSS Positioning), I thought the writing was excellent. It was easy to understand, and I think that a non-tech audience would agree. The only thing I can think of to improve it is to include some visual examples along with the CSS code needed to set the position.

Well, I hope week 2 has been good to you. Here we come, week 3!

'Tine

**Comment by chagers** [comment]
Hey! Thanks mucho for the feedback. I guess I didn't realize it's probably proper protocol to go in and comment, then close an issue when it's raised. Still learning :)
I've gone in and added a couple visual examples for my tech blog this week, so thanks for the recommendation! 

Hope week 3 went well for you.

-christine
