### ISSUE TITLE
T3 blog review

### ISSUE THREAD

**Issue by TimCannady** [chagers/chagers.github.io#6]
Hi Christine,

I really enjoyed your blog post: T3 Arrays and Hashes. I naturally read it after doing my own, and I'd definitely rate yours a step ahead of my own!

You've done a great job at explaining complex items in a way that doesn't take any shortcuts, but also manages to remain succinct. This is perfect when it comes to a blog post - makes things much more digestible.

The only feedback I have is maybe for "what's next". You've done such a great job, perhaps there's room to expand on your second to last paragraph: "The main difference between..."  Adding a little example of array versus hash access and iteration could really make this an all-in-one post, and in well under 500 words.  Great work!

**Comment by chagers** [comment]
Thanks for the feedback, Tim!

Really appreciate the note about the what's next section. I thought I may have rushed the ending a bit, and that confirms it. :)

Cheers!
